### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by thororen1234**
Fixed most icons if not all with help from davart154

### CODE REVIEW

**Comment by thororen1234** [comment]
New mute icon looks better if im seeing the right one

**Comment by thororen1234** [comment]
Nevermind its the right icon

**Review by MrDiamondDog — CHANGES_REQUESTED** [review]
Just fyi if you use a different file it will stop working for everyone who has this theme

**Comment by thororen1234** [comment]
ight ill change it now

**Comment by MrDiamondDog** [comment]
Looks good, thank you!

**Pull request merged**
